#!/usr/bin/env bash

root_dir="$(cd $(dirname "${BASH_SOURCE[1]}") && pwd)/keys/ssh"

names=("alire_alavi_github" "lavirez_github")



# Decrypt the SSH keys
for name in "${names[@]}"; do
    touch $HOME/.ssh/$name
    touch $HOME/.ssh/$name.pub
    gpg --quiet --batch --yes --decrypt --passphrase="$SSH_KEY_PASS" \
        --output "$HOME/.ssh/$name" "$root_dir/$name.gpg"

    gpg --quiet --batch --yes --decrypt --passphrase="$SSH_KEY_PASS" \
        --output "$HOME/.ssh/$name.pub" "$root_dir/$name.pub.gpg"

    chmod 600 "$HOME/.ssh/$name"
done

# Copy the config
cp "$root_dir/config" ~/.ssh/
